"""Transparency labels — what an actual reader sees.

Three variants, one per verdict. Rules I held to:
  * plain language, no jargon ("classifier", "logit", "raw score" are banned)
  * the *text* changes with confidence, not just a number
  * any label that could be an accusation also names the appeal path

The wording here is the source of truth and is reproduced verbatim in the README.
"""
from config import LIKELY_AI, LIKELY_HUMAN, UNCERTAIN
from scoring import confidence_band

# Confidence sentence injected into the human/AI labels so identical verdicts at
# different confidence levels read differently.
_CONFIDENCE_SENTENCE = {
    "high": "We're fairly confident in this estimate.",
    "medium": "We're only moderately confident in this estimate.",
    "low": "Our confidence in this estimate is low.",
}


def make_label(verdict, confidence):
    """Return the reader-facing transparency label string for a verdict."""
    band = confidence_band(confidence)
    conf_sentence = _CONFIDENCE_SENTENCE[band]
    pct = round(confidence * 100)

    if verdict == LIKELY_AI:
        return (
            f"🤖 Likely AI-generated. Our analysis suggests this text was most "
            f"likely produced by an AI tool. Two independent checks — a "
            f"language-model review and a writing-style analysis — pointed the "
            f"same way. {conf_sentence} No automated check is perfect. If you "
            f"wrote this yourself, you can appeal and a person will review it. "
            f"(confidence {pct}%)"
        )

    if verdict == LIKELY_HUMAN:
        return (
            f"✍️ Likely written by a person. Our analysis suggests this text was "
            f"most likely written by a human. Both of our checks pointed the same "
            f"way. {conf_sentence} This is our best estimate, not a guarantee. "
            f"(confidence {pct}%)"
        )

    # UNCERTAIN
    return (
        "🤔 Inconclusive. We couldn't confidently tell whether this was written "
        "by a person or generated by AI — our two checks either disagreed or "
        "landed in the middle. We're showing this as uncertain rather than "
        f"guessing. Treat it as 'not enough signal to call.' (confidence {pct}%)"
    )


# Short headline used in compact UIs / the analytics view.
HEADLINE = {
    LIKELY_AI: "Likely AI-generated",
    LIKELY_HUMAN: "Likely written by a person",
    UNCERTAIN: "Inconclusive",
}
