"""Signal 1 — LLM judge (Groq llama-3.3-70b-versatile).

This is the LLM-as-judge pattern: we don't ask the model to be helpful, we ask it
to make a structured decision the pipeline consumes. It reads the text the way a
person would and estimates P(AI). Its output is one noisy vote, not gospel —
AI detection isn't something any model does reliably, so I treat it accordingly.

On any failure (no key, network error, unparseable reply) it returns p_ai = 0.5
with reliable=False. A 0.5 lands in the "uncertain" band, which is the safe place
to fail on a writing platform — we'd rather say "not sure" than falsely accuse.
"""
import json
import re

from config import GROQ_API_KEY, GROQ_MODEL

_SYSTEM_PROMPT = (
    "You are a forensic text analyst. Estimate the probability that a passage was "
    "generated by an AI language model rather than written by a human.\n"
    "Weigh signals like: generic phrasing, even/uniform rhythm, over-hedging, "
    "absence of specific lived detail or idiosyncrasy (more AI) versus specific "
    "concrete detail, irregular rhythm, personal voice, and surprising word "
    "choices (more human).\n"
    'Respond with ONLY a compact JSON object: {"p_ai": <float 0..1>, '
    '"reason": "<one short sentence>"}.\n'
    "p_ai = 0.0 means certainly human, 1.0 means certainly AI. "
    "Output nothing outside the JSON."
)

# Appended when re-scoring an appeal. The creator's explanation is new information,
# but it is self-interested, so the judge stays skeptical: a plausible account of
# WHY human writing looks AI-like (non-native English, formal training, heavy
# editing) may lower the estimate; a bare claim of authorship must not.
_APPEAL_PROMPT = (
    "\n\nA creator is contesting an AI-generated label for this text and offers an "
    "explanation (below). Re-assess p_ai taking the explanation into account, but "
    "stay skeptical: anyone can claim they wrote something. Lower your estimate "
    "ONLY if the explanation plausibly accounts for the AI-like features of the "
    "text; do not lower it merely because authorship is asserted.\n"
    "Creator's explanation: "
)

# Lazily-created client so importing this module never requires a key.
_client = None


def _get_client():
    global _client
    if _client is None:
        from groq import Groq
        _client = Groq(api_key=GROQ_API_KEY)
    return _client


def _parse_p_ai(raw):
    """Pull p_ai (and reason) out of the model reply, defensively."""
    try:
        obj = json.loads(raw)
        p = float(obj["p_ai"])
        reason = str(obj.get("reason", "")).strip()
        return max(0.0, min(1.0, p)), reason
    except Exception:
        pass
    # Fallback: find a JSON-ish blob, then any float.
    m = re.search(r'"p_ai"\s*:\s*([0-9]*\.?[0-9]+)', raw)
    if m:
        p = max(0.0, min(1.0, float(m.group(1))))
        rm = re.search(r'"reason"\s*:\s*"([^"]*)"', raw)
        return p, (rm.group(1) if rm else "")
    m = re.search(r"([0-9]*\.?[0-9]+)", raw)
    if m:
        val = float(m.group(1))
        if val > 1:  # model gave a percentage
            val = val / 100.0
        return max(0.0, min(1.0, val)), ""
    raise ValueError(f"could not parse p_ai from: {raw!r}")


def llm_score(text, appeal_context=None):
    """Return P(AI) from the LLM judge plus its rationale.

    Args:
      text:           the passage to judge
      appeal_context: optional creator reasoning. When present, the judge re-scores
                      the text in light of the explanation (skeptically).

    Returns:
      {"p_llm": float 0..1, "reason": str, "reliable": bool}
    """
    if not GROQ_API_KEY:
        return {"p_llm": 0.5, "reason": "llm_unavailable (no API key)", "reliable": False}

    system = _SYSTEM_PROMPT
    if appeal_context:
        system = _SYSTEM_PROMPT + _APPEAL_PROMPT + str(appeal_context)

    try:
        client = _get_client()
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": text},
            ],
            temperature=0,
            max_tokens=120,
            response_format={"type": "json_object"},
        )
        raw = resp.choices[0].message.content.strip()
        p, reason = _parse_p_ai(raw)
        return {"p_llm": round(p, 4), "reason": reason or "(no reason given)",
                "reliable": True}
    except Exception as exc:  # network, auth, parse — all fail safe to uncertain
        return {"p_llm": 0.5, "reason": f"llm_error: {type(exc).__name__}",
                "reliable": False}


if __name__ == "__main__":
    import sys
    sample = sys.argv[1] if len(sys.argv) > 1 else (
        "ok so i finally tried that ramen place downtown and honestly? "
        "underwhelming. way too much sodium, was thirsty for hours."
    )
    print(json.dumps(llm_score(sample), indent=2))
